server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/kyc?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    open-in-view: false

  kafka:
    producer:
      bootstrap-servers: localhost:9092

apick:
  base-url: https://apick.app
  auth-key: abe6212197d18fd666e211c6f7114002

user:
  base-url: http://localhost:8081

# 로깅 설정 - 개인정보 보호를 위한 로그 레벨 관리
logging:
  level:
    # 기본 로그 레벨
    root: INFO
    # KYC 관련 패키지는 INFO 레벨로 제한하여 DEBUG 정보 노출 방지
    "[com.ddiring.Backend_Kyc.integration.apick]": INFO
    # Spring Security, WebClient 등의 상세 로그 제한
    "[org.springframework.web.reactive.function.client]": WARN
    "[reactor.netty.http.client]": WARN
  pattern:
    # 로그 패턴에서 민감한 정보 노출 방지
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"